### ISSUE TITLE
Can't run tests using Pytest

### ISSUE THREAD

**Issue by Tylersuard** [Mirascope/mirascope#209]
ImportError while loading conftest 'C:\Users\tyler\OneDrive\Desktop\App Ideas and Work\mirascope\mirascope\tests\conftest.py'.
tests\conftest.py:6: in <module>
    from anthropic.types import (
E   ModuleNotFoundError: No module named 'anthropic'

**Comment by Tylersuard** [comment]
Ok I think I solved that issue, now I am getting a different issue: Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "C:\Python310\lib\site.py", line 186, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "C:\Users\tyler\OneDrive\Desktop\App Ideas and Work\mirascope\mirascope\mirascope\types.py", line 1, in <module>
    from typing import TypeVar
  File "C:\Python310\lib\typing.py", line 25, in <module>
    import contextlib
  File "C:\Python310\lib\contextlib.py", line 6, in <module>
    from functools import wraps
  File "C:\Python310\lib\functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (C:\Users\tyler\OneDrive\Desktop\App Ideas and Work\mirascope\mirascope\mirascope\types.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site.py", line 617, in <module>
    main()
  File "C:\Python310\lib\site.py", line 603, in main
    known_paths = addusersitepackages(known_paths)
  File "C:\Python310\lib\site.py", line 343, in addusersitepackages
    addsitedir(user_site, known_paths)
  File "C:\Python310\lib\site.py", line 226, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\Python310\lib\site.py", line 196, in addpackage
    import traceback
  File "C:\Python310\lib\traceback.py", line 5, in <module>
    import linecache
  File "C:\Python310\lib\linecache.py", line 8, in <module>
    import functools
  File "C:\Python310\lib\functools.py", line 22, in <module>
    from types import GenericAlias
  File "C:\Users\tyler\OneDrive\Desktop\App Ideas and Work\mirascope\mirascope\mirascope\types.py", line 1, in <module>
    from typing import TypeVar
  File "C:\Python310\lib\typing.py", line 25, in <module>
    import contextlib
  File "C:\Python310\lib\contextlib.py", line 6, in <module>
    from functools import wraps
ImportError: cannot import name 'wraps' from partially initialized module 'functools' (most likely due to a circular import) (C:\Python310\lib\functools.py)

**Comment by willbakst** [comment]
I just pulled from dev and ran `poetry run pytest tests` with no issue.

Are you running this from current dev or from a different fork/branch?

**Comment by willbakst** [comment]
I am going to close this issue as I haven't been able to reproduce locally. If this problem still persists, please reopen this issue with additional details for how to reproduce.
