### ISSUE TITLE
Cache control not working

### ISSUE THREAD

**Issue by ramon-prieto** [Mirascope/mirascope#618]
### Description

I'm getting the following error whenever calling a function with cache control enabled

```log
04:53:03.126 Stacktrace: Traceback (most recent call last):
executor-1      |   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
executor-1      |     result = fn(*args, **kwargs)
executor-1      |              ^^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/mirascope/core/base/_extract.py", line 151, in inner
executor-1      |     call_response = create_decorator(fn=fn, **create_decorator_kwargs)(
executor-1      |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/mirascope/core/base/_create.py", line 211, in inner
executor-1      |     response = create(stream=False, **call_kwargs)
executor-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/anthropic.py", line 107, in _sentry_patched_create
executor-1      |     raise exc from None
executor-1      |   File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/anthropic.py", line 103, in _sentry_patched_create
executor-1      |     result = f(*args, **kwargs)
executor-1      |              ^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/anthropic/_utils/_utils.py", line 274, in wrapper
executor-1      |     return func(*args, **kwargs)
executor-1      |            ^^^^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/anthropic/resources/messages.py", line 878, in create
executor-1      |     return self._post(
executor-1      |            ^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/anthropic/_base_client.py", line 1260, in post
executor-1      |     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
executor-1      |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/anthropic/_base_client.py", line 937, in request
executor-1      |     return self._request(
executor-1      |            ^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/anthropic/_base_client.py", line 1041, in _request
executor-1      |     raise self._make_status_error_from_response(err.response) from None
executor-1      | anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'system: text content blocks must be non-empty'}}
executor-1      | 
executor-1      | The above exception was the direct cause of the following exception:
executor-1      | 
executor-1      | Traceback (most recent call last):
executor-1      |   File "/src/app/agents/patient_matcher.py", line 154, in _execute
executor-1      |     eligibility_answer = self.answer_question(
executor-1      |                          ^^^^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/mirascope/integrations/_middleware_factory.py", line 212, in wrapper
executor-1      |     result = fn(*args, **kwargs)
executor-1      |              ^^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
executor-1      |     return copy(f, *args, **kw)
executor-1      |            ^^^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
executor-1      |     do = self.iter(retry_state=retry_state)
executor-1      |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
executor-1      |     result = action(retry_state)
executor-1      |              ^^^^^^^^^^^^^^^^^^^
executor-1      |   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 419, in exc_check
executor-1      |     raise retry_exc from fut.exception()
executor-1      | tenacity.RetryError: RetryError[<Future at 0xffff59178140 state=finished raised BadRequestError>]
```

My function looks like this

```py
@anthropic.call(
        model="claude-3-5-sonnet-20240620",
        client=AnthropicVertex(
            project_id=general_config.project_id,
            region=general_config.anthropic_region,
        ),
        response_model=EligibilityAnswer,
        json_mode=True,
        call_params={
            "temperature": 0.2,
            "max_tokens": 1024,
            "extra_headers": {"anthropic-beta": "prompt-caching-2024-07-31"},
        },
    )
    def answer_question(self, question: str, documents: list[str]) -> EligibilityAnswer:
        messages = [
            Messages.System(
                content=[
                    TextPart(
                        type="text",
                        text="You are a confident and detail-oriented medical expert tasked with answering yes/no questions about a patient's eligibility for a clinical trial.",
                    ),
                    CacheControlPart(type="cache_control", cache_type="ephemeral"),
                ],
            ),
            Messages.User(
                content=[
                    TextPart(
                        type="text",
                        text=INSTRUCTIONS_PROMPT,
                    ),
                    CacheControlPart(type="cache_control", cache_type="ephemeral"),
                ],
            ),
            Messages.User(
                content=[
                    TextPart(
                        type="text",
                        text=PATIENT_PROFILE_PROMPT,
                    ),
                ],
            ),
        ]
        print("~~~~~~~~~~~~~" * 20)
        print(messages)
        print("~~~~~~~~~~~~~" * 20)
        return {
            "messages": messages,
            "computed_fields": {"today": now().format("YYYY-MM-DD")},
        }
```

### Python, Mirascope & OS Versions, related packages (not required)

```TOML
mirascope version: 1.4
```

**Comment by willbakst** [comment]
Good catch! Fix for this released in `v1.4.1` :)

**Comment by ramon-prieto** [comment]
This is still failing when using the `AnthropicVertex` client

```log
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.0.content.0.text.cache_control: Extra inputs are not permitted'}}
```

**Comment by ramon-prieto** [comment]
That makes sense. Thanks!
